//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34014
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MUSIC.MVVM.ReferenceServiceSong {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ReferenceServiceSong.ISongService")]
    public interface ISongService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISongService/GetSong", ReplyAction="http://tempuri.org/ISongService/GetSongResponse")]
        MUSIC.ENTITIES.Song[] GetSong();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISongService/GetAlbum", ReplyAction="http://tempuri.org/ISongService/GetAlbumResponse")]
        MUSIC.ENTITIES.Album[] GetAlbum();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISongService/GetLists", ReplyAction="http://tempuri.org/ISongService/GetListsResponse")]
        MUSIC.ENTITIES.ListSong[] GetLists();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISongService/GetCompleteSongs", ReplyAction="http://tempuri.org/ISongService/GetCompleteSongsResponse")]
        MUSIC.ENTITIES.Song[] GetCompleteSongs();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISongService/AddPlayList", ReplyAction="http://tempuri.org/ISongService/AddPlayListResponse")]
        MUSIC.ENTITIES.PlayList AddPlayList(MUSIC.ENTITIES.PlayList oPlayList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISongService/AddList", ReplyAction="http://tempuri.org/ISongService/AddListResponse")]
        MUSIC.ENTITIES.ListSong AddList(MUSIC.ENTITIES.ListSong oList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISongService/GetSongsByList", ReplyAction="http://tempuri.org/ISongService/GetSongsByListResponse")]
        MUSIC.ENTITIES.Song[] GetSongsByList(MUSIC.ENTITIES.ListSong oListSong);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISongServiceChannel : MUSIC.MVVM.ReferenceServiceSong.ISongService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SongServiceClient : System.ServiceModel.ClientBase<MUSIC.MVVM.ReferenceServiceSong.ISongService>, MUSIC.MVVM.ReferenceServiceSong.ISongService {
        
        public SongServiceClient() {
        }
        
        public SongServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SongServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SongServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SongServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public MUSIC.ENTITIES.Song[] GetSong() {
            return base.Channel.GetSong();
        }
        
        public MUSIC.ENTITIES.Album[] GetAlbum() {
            return base.Channel.GetAlbum();
        }
        
        public MUSIC.ENTITIES.ListSong[] GetLists() {
            return base.Channel.GetLists();
        }
        
        public MUSIC.ENTITIES.Song[] GetCompleteSongs() {
            return base.Channel.GetCompleteSongs();
        }
        
        public MUSIC.ENTITIES.PlayList AddPlayList(MUSIC.ENTITIES.PlayList oPlayList) {
            return base.Channel.AddPlayList(oPlayList);
        }
        
        public MUSIC.ENTITIES.ListSong AddList(MUSIC.ENTITIES.ListSong oList) {
            return base.Channel.AddList(oList);
        }
        
        public MUSIC.ENTITIES.Song[] GetSongsByList(MUSIC.ENTITIES.ListSong oListSong) {
            return base.Channel.GetSongsByList(oListSong);
        }
    }
}
